### ISSUE TITLE
Duplicate SAC Form changes and added fields

### ISSUE THREAD

**Issue by db-lyon** [Nimba-Solutions/NYS-Foundations#3]

**Comment by PonchoMcGee** [comment]
REVISIONS to Duplicate SAC Form: 
Remove Program Information Section

Add this text to the top of the form: 
If you are requesting multiple transcripts/certificates, you will need to submit this form one time for each.  If you are requesting more than two transcripts/certificates and would like to make this transaction over the phone, please email Lea, [info@networkforyouthsuccess.org](mailto:info@networkforyouthsuccess.org).

 

NOTE: For Health And Safety Certificates, sign into your [ECETP Account.](https://www.ecetp.pdp.albany.edu/index.aspx)



ADD DROP DOWN for the following items all priced at $25:

Duplicate Conference Certificate

Duplicate SAC Credential Certificate

Duplicate Distance Learning Transcript

Duplicate Virtual Transcript

Duplication Training Transcript

Duplicate SAC Credential Goals (for renewal)



Please add the following fields: 

List the Name of the individual on the certificate you are requesting*

List the name of the training you are requesting a transcript for*

If requesting a SAC Distance Learning or Virtual Transcript, please indicate the semester you are requesting a transcript for 

For Training Certificates, Goals, SAC Endorsement Certificates, and Conference Transcripts enter the MONTH and YEAR of the event



Please add the following text at the end before payment

Your Request

Once your request is received, your documents will be sent within 15 business days.
